### ISSUE TITLE
not exist vue-lighthouse-viewer/dist/vuelighthouseviewer.css

### ISSUE THREAD

**Issue by kimsangsoo** [dvelasquez/lighthouse-viewer#4]
npm install vue-lighthouse-viewer

**Comment by dvelasquez** [comment]
Thanks for reporting!
Now is not necessary to import the CSS manually.
See the demo: https://github.com/dvelasquez/lighthouse-viewer/blob/master/packages/demo/src/index.ts

I will fix the README.md with this change ;)

**Comment by dvelasquez** [comment]
@kimsangsoo If you still have a problem, feel free of reopen the issue
