### ISSUE TITLE
Declaration file not found in lighthouse-viewer package

### ISSUE THREAD

**Issue by Vwings** [dvelasquez/lighthouse-viewer#767]
Hello, @dvelasquez , The declaration file `./types/types.d.ts` is not in the `lighthouse-viewer` package now.

version: `0.1.64`

**Comment by dvelasquez** [comment]
Hi @Vwings , the new version `0.1.66` should have this fixed. If that is not the case, feel free to reopen the issue.

**Comment by Vwings** [comment]
Thanks @dvelasquez , the declaration file exists now. 
`types.d.ts` imports some declaration files in `lighthouse` package:
```
lighthouse/report/types/report-renderer.d
lighthouse/types/lhr/audit-result.d
```
Currently `lighthouse` package is a devDependency, it's not installed when installing `lighthouse-viewer`.
